export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL"

export const GET_COURSE_CATEGORY_SUCCESS = "GET_COURSE_CATEGORY_SUCCESS"
export const GET_COURSE_CATEGORY_FAIL = "GET_COURSE_CATEGORY_FAIL"

export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS"
export const GET_COMPANY_LIST_FAIL = "GET_COMPANY_LIST_FAIL"

export const GET_MY_COURSES_SUCCESS = "GET_MY_COURSES_SUCCESS"
export const GET_MY_COURSES_FAIL = "GET_MY_COURSES_FAIL"

export const GET_PUBLIC_COURSES_SUCCESS = "GET_PUBLIC_COURSES_SUCCESS"
export const GET_PUBLIC_COURSES_FAIL = "GET_PUBLIC_COURSES_FAIL"

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";